[package]
name = "star_gate"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the StarGate gRPC server.
name = "stargate-server"
path = "src/bin/stargate_server.rs"

[dependencies]
approx = "0.5.1"
clap = { version = "4.3.19", features = ["derive"] }
env_logger = "0.10.0"
image = "0.24.6"
imageproc = "0.23.0"
log = "0.4.19"
prost = "0.11.9"
prost-types = "0.11.9"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.9.2"
tonic-web = "0.9.2"

[build-dependencies]
tonic-build = "0.9"
prost-build = "0.11.9"
